title: WCST2019
description: Waves, coherent structures, and turbulence 2019
tags: [waves, coherent structures, turbulence, WCST2019, wave turbulence, WT SIG]

url: https://davideproment.github.io/WCST2019/

author: Davide Proment

logo: logo_Blue.png
google_analytics: UA-145404605-1

theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: false
  collections: false

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
